name: bell_memo
description: A simple Flutter demo application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.2
  flutter_markdown: ^0.7.7+1
  flutter_quill: ^11.5.0
  markdown_quill: ^4.3.0
  open_filex: ^4.7.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  webdav_client: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/bell.png

